//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBlog.DataAccess.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public System.Guid PostId { get; set; }
        public int PostCode { get; set; }
        public string Title { get; set; }
        public bool Visiable { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<short> CommentCount { get; set; }
        public System.Guid AuthorId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Content { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
